import i18n from "@/i18/i18";
import {
  CreateReport,
  CustomReportForm,
  ExpenseReport,
  GenericObject,
  TripReport,
  WorkflowBranch,
  WorkflowStep,
} from "./types";

const AUTH_PAGES = ["/login", "/register"];

export const isAuthPages = (url: string) =>
  AUTH_PAGES.some((page) => page.startsWith(url));

export const imageRawBaseUrl = "https://masraffphoto.blob.core.windows.net/";

const userString =
  typeof localStorage !== "undefined" && localStorage.getItem("user");
export const globalUserObject = userString && JSON.parse(userString);

const today = new Date();
export const minDate = new Date(
  today.getFullYear() - 5,
  today.getMonth(),
  today.getDate()
);
export const maxDate = new Date(
  today.getFullYear(),
  today.getMonth(),
  today.getDate()
);

export const expenseStatus: { [index: number]: string } = {
  1: i18n.t("labels.processing"),
  2: i18n.t("labels.ready"),
  3: i18n.t("labels.waiting"),
  4: i18n.t("labels.approved"),
  5: i18n.t("labels.rejected"),
  6: i18n.t("labels.archived"),
  7: i18n.t("labels.completed"),
  8: i18n.t("labels.missingData"),
  9: i18n.t("labels.inQueue"),
  10: i18n.t("labels.waitingForPayment"),
  11: i18n.t("labels.errorInPayment"),
  12: i18n.t("labels.paymentCompleted"),
  13: i18n.t("labels.loading"),
  14: i18n.t("labels.infoRequired"),
  15: i18n.t("labels.uploadError"),
};

export const formStatus = {
  0: i18n.t("labels.processing"),
  1: i18n.t("labels.ready"),
  2: i18n.t("labels.waiting"),
  3: i18n.t("labels.approved"),
  4: i18n.t("labels.rejected"),
  5: i18n.t("labels.archived"),
  6: i18n.t("labels.deleted"),
  7: i18n.t("labels.completed"),
  8: i18n.t("labels.waitingForPayment"),
  9: i18n.t("labels.errorInPayment"),
  10: i18n.t("labels.paymentCompleted"),
  12: i18n.t("labels.sentForApproval"),
};

export const paymentMethods = {
  0: i18n.t("labels.personalCreditCard"),
  1: i18n.t("labels.enterpriseCreditCard"),
  2: i18n.t("labels.paidByCompany"),
  3: i18n.t("labels.cash"),
  4: i18n.t("labels.cashAdvance"),
};

export const expenseSearchTypes = [
  {
    id: 1,
    name: i18n.t("labels.expenseNo"),
  },
  {
    id: 2,
    name: i18n.t("labels.name"),
  },
  {
    id: 3,
    name: i18n.t("labels.lastName"),
  },
  {
    id: 4,
    name: i18n.t("labels.email"),
  },
  {
    id: 5,
    name: i18n.t("labels.merchant"),
  },
];

export const expenseReportSearchTypes = [
  {
    id: 1,
    name: i18n.t("labels.select"),
  },
  {
    id: 1,
    name: i18n.t("labels.reportNo"),
  },
  {
    id: 2,
    name: i18n.t("labels.reportName"),
  },
  {
    id: 5,
    name: i18n.t("labels.name"),
  },
  {
    id: 6,
    name: i18n.t("labels.lastName"),
  },
  {
    id: 3,
    name: i18n.t("labels.email"),
  },
  {
    id: 4,
    name: i18n.t("labels.approverEmail"),
  },
];

export const statusList = [
  { id: 1, name: i18n.t("labels.processing") },
  { id: 2, name: i18n.t("labels.ready") },
  { id: 3, name: i18n.t("labels.waitingForApproval") },
  { id: 4, name: i18n.t("labels.approved") },
  { id: 5, name: i18n.t("labels.rejected") },
  { id: 6, name: i18n.t("labels.archived") },
  { id: 7, name: i18n.t("labels.deleted") },
  { id: 8, name: i18n.t("labels.completed") },
  { id: 9, name: i18n.t("labels.editWaiting") },
  { id: 10, name: i18n.t("labels.inQueue") },
  { id: 11, name: i18n.t("labels.waitingForPayment") },
  { id: 12, name: i18n.t("labels.errorInPayment") },
  { id: 13, name: i18n.t("labels.paymentCompleted") },
  { id: 14, name: i18n.t("labels.loading") },
  { id: 15, name: i18n.t("labels.infoRequired") },
  { id: 16, name: i18n.t("labels.uploadError") },
];

export const reportStatusList = [
  { id: 0, name: i18n.t("labels.processing") },
  { id: 1, name: i18n.t("labels.ready") },
  { id: 2, name: i18n.t("labels.waitingForApproval") },
  { id: 3, name: i18n.t("labels.approved") },
  { id: 4, name: i18n.t("labels.rejected") },
  { id: 5, name: i18n.t("labels.archived") },
  { id: 6, name: i18n.t("labels.deleted") },
  { id: 7, name: i18n.t("labels.completed") },
  { id: 8, name: i18n.t("labels.waitingForPayment") },
  { id: 9, name: i18n.t("labels.errorInPayment") },
  { id: 10, name: i18n.t("labels.paymentCompleted") },
  { id: 12, name: i18n.t("labels.sentForApproval") },
  { id: 13, name: i18n.t("labels.editWaiting") },
];

export const expenseCustomFormsStatusList = [
  { id: 1, name: i18n.t("labels.processing") },
  { id: 2, name: i18n.t("labels.ready") },
  { id: 3, name: i18n.t("labels.waitingForApproval") },
  { id: 4, name: i18n.t("labels.approved") },
  { id: 5, name: i18n.t("labels.rejected") },
  { id: 6, name: i18n.t("labels.archived") },
  { id: 7, name: i18n.t("labels.deleted") },
  { id: 8, name: i18n.t("labels.completed") },
  { id: 9, name: i18n.t("labels.editWaiting") },
  { id: 10, name: i18n.t("labels.inQueue") },
  { id: 11, name: i18n.t("labels.waitingForPayment") },
  { id: 12, name: i18n.t("labels.errorInPayment") },
  { id: 13, name: i18n.t("labels.paymentCompleted") },
  { id: 14, name: i18n.t("labels.loading") },
  { id: 15, name: i18n.t("labels.infoRequired") },
  { id: 16, name: i18n.t("labels.uploadError") },
];

export const paymentMethodList = [
  { id: 0, name: i18n.t("labels.personalCreditCard") },
  { id: 1, name: i18n.t("labels.enterpriseCreditCard") },
  { id: 2, name: i18n.t("labels.paidByCompany") },
  { id: 3, name: i18n.t("labels.cash") },
  { id: 4, name: i18n.t("labels.cashAdvance") },
];
export const taxPertangeList = [
  { id: 0, name: "0" },
  { id: 1, name: "1" },
  { id: 8, name: "8" },
  { id: 10, name: "10" },
  { id: 18, name: "18" },
  { id: 20, name: "20" },
];

export const availablePaymentMethods = [
  {
    id: 1,
    name: i18n.t("labels.enterpriseCreditCard"),
  },
  {
    id: 3,
    name: i18n.t("labels.cash"),
  },
  {
    id: 4,
    name: i18n.t("labels.cashAdvance"),
  },
];

export const deliveryStatusList: GenericObject[] = [
  { id: false, name: i18n.t("labels.notDelivered") },
  { id: true, name: i18n.t("labels.delivered") },
];

export const currencyList = [
  { name: "TL", id: 1 },
  { name: "USD", id: 2 },
  { name: "EUR", id: 3 },
  { name: "GBP", id: 4 },
  { name: "CHF", id: 5 },
  { name: "SEK", id: 6 },
  { name: "CAD", id: 7 },
  { name: "KWD", id: 8 },
  { name: "SAR", id: 9 },
  { name: "DKK", id: 10 },
  { name: "AUD", id: 11 },
  { name: "AED", id: 12 },
  { name: "AFN", id: 13 },
  { name: "ALL", id: 14 },
  { name: "AMD", id: 15 },
  { name: "ANG", id: 16 },
  { name: "AOA", id: 17 },
  { name: "ARS", id: 18 },
  { name: "AWG", id: 20 },
  { name: "AZN", id: 21 },
  { name: "BAM", id: 22 },
  { name: "BBD", id: 23 },
  { name: "BDT", id: 24 },
  { name: "BGN", id: 25 },
  { name: "BHD", id: 26 },
  { name: "BIF", id: 27 },
  { name: "BMD", id: 28 },
  { name: "BND", id: 29 },
  { name: "BOB", id: 30 },
  { name: "BRL", id: 31 },
  { name: "BSD", id: 32 },
  { name: "BTC", id: 33 },
  { name: "BTN", id: 34 },
  { name: "BWP", id: 35 },
  { name: "BYN", id: 36 },
  { name: "BZD", id: 37 },
  { name: "CDF", id: 38 },
  { name: "CLP", id: 39 },
  { name: "CNY", id: 40 },
  { name: "COP", id: 41 },
  { name: "CRC", id: 42 },
  { name: "CUP", id: 43 },
  { name: "CVE", id: 44 },
  { name: "CZK", id: 45 },
  { name: "DJF", id: 46 },
  { name: "DOP", id: 47 },
  { name: "DZD", id: 48 },
  { name: "EGP", id: 49 },
  { name: "ERN", id: 50 },
  { name: "ETB", id: 51 },
  { name: "FJD", id: 52 },
  { name: "FKP", id: 53 },
  { name: "GEL", id: 54 },
  { name: "GHS", id: 55 },
  { name: "GIP", id: 56 },
  { name: "GMD", id: 57 },
  { name: "GNF", id: 58 },
  { name: "GTQ", id: 59 },
  { name: "GYD", id: 60 },
  { name: "HKD", id: 61 },
  { name: "HNL", id: 62 },
  { name: "HRK", id: 63 },
  { name: "HTG", id: 64 },
  { name: "HUF", id: 65 },
  { name: "IDR", id: 66 },
  { name: "ILS", id: 67 },
  { name: "INR", id: 68 },
  { name: "IQD", id: 69 },
  { name: "IRR", id: 70 },
  { name: "ISK", id: 71 },
  { name: "JMD", id: 72 },
  { name: "JOD", id: 73 },
  { name: "JPY", id: 74 },
  { name: "KES", id: 75 },
  { name: "KGS", id: 76 },
  { name: "KHR", id: 77 },
  { name: "KMF", id: 78 },
  { name: "KPW", id: 79 },
  { name: "KRW", id: 80 },
  { name: "KYD", id: 81 },
  { name: "KZT", id: 82 },
  { name: "LAK", id: 83 },
  { name: "LBP", id: 84 },
  { name: "LKR", id: 85 },
  { name: "LRD", id: 86 },
  { name: "LSL", id: 87 },
  { name: "LYD", id: 88 },
  { name: "MAD", id: 89 },
  { name: "MDL", id: 90 },
  { name: "MGA", id: 91 },
  { name: "MKD", id: 92 },
  { name: "MMK", id: 93 },
  { name: "MNT", id: 94 },
  { name: "MOP", id: 95 },
  { name: "MRO", id: 96 },
  { name: "MUR", id: 97 },
  { name: "MVR", id: 98 },
  { name: "MWK", id: 99 },
  { name: "MXN", id: 100 },
  { name: "MYR", id: 101 },
  { name: "MZN", id: 102 },
  { name: "NAD", id: 103 },
  { name: "NGN", id: 104 },
  { name: "NIO", id: 105 },
  { name: "NOK", id: 106 },
  { name: "NPR", id: 107 },
  { name: "NZD", id: 108 },
  { name: "OMR", id: 109 },
  { name: "PAB", id: 110 },
  { name: "PEN", id: 111 },
  { name: "PGK", id: 112 },
  { name: "PHP", id: 113 },
  { name: "PKR", id: 114 },
  { name: "PLN", id: 115 },
  { name: "PYG", id: 116 },
  { name: "QAR", id: 117 },
  { name: "RON", id: 118 },
  { name: "RSD", id: 119 },
  { name: "RUB", id: 120 },
  { name: "RWF", id: 121 },
  { name: "SBD", id: 123 },
  { name: "SCR", id: 124 },
  { name: "SDG", id: 125 },
  { name: "SGD", id: 126 },
  { name: "SHP", id: 127 },
  { name: "SLL", id: 128 },
  { name: "SOS", id: 129 },
  { name: "SRD", id: 130 },
  { name: "STD", id: 131 },
  { name: "SVC", id: 132 },
  { name: "SYP", id: 133 },
  { name: "SZL", id: 134 },
  { name: "THB", id: 135 },
  { name: "TJS", id: 136 },
  { name: "TMT", id: 137 },
  { name: "TND", id: 138 },
  { name: "TOP", id: 139 },
  { name: "TTD", id: 141 },
  { name: "TWD", id: 142 },
  { name: "TZS", id: 143 },
  { name: "UAH", id: 144 },
  { name: "UGX", id: 145 },
  { name: "UYU", id: 146 },
  { name: "UZS", id: 147 },
  { name: "VEF", id: 148 },
  { name: "VND", id: 149 },
  { name: "VUV", id: 150 },
  { name: "WST", id: 151 },
  { name: "XAF", id: 152 },
  { name: "XCD", id: 153 },
  { name: "XDR", id: 154 },
  { name: "XOF", id: 155 },
  { name: "XPF", id: 156 },
  { name: "YER", id: 157 },
  { name: "ZAR", id: 158 },
  { name: "ZMW", id: 159 },
  { name: "ZWB", id: 160 },
];

export const defaultExpenseFilter = {
  includes: "user, expenseType",
  clientId: "adminApp",
  page: 0,
  pageSize: 10,
  ascending: "false",
  searchTypeId: 0,
};

export const emptyExpense = {
  id: null,
  name: "",
  approverUserId: null,
  userId: null,
  amount: null,
  note: "",
  billable: false,
  tag_LookupId: null,
  status: 0,
  taxPercentage: 0,
  taxAmount: 0,
  currencyRate: 1,
  reimbursable: false,
  currency: 1,
  expenseTypeId: 0,
  currencyText: "TL",
  isLimitExceeded: false,
  paymentMethod: 3,
  tag_Lookup: {},
  conversionAmount: null,
  sourceType: 2,
  expenseDate: "",
  receiptNumber: "",
  merchant: "",
  reportId: null,
  ohpCodeId: null,
  attendeesList: [],
  attendeesNumber: 1,
  expenseType: { name: "" },
};

export const emptyExpenseReport: ExpenseReport = {
  advanceReport: null,
  advanceReportId: 0,
  approvedDate: "",
  approver: {},
  approverUserId: 0,
  comment: "",
  createDate: "",
  currency: 0,
  currencyText: "",
  customFields: null,
  customReportType: null,
  denialNote: "",
  description: "",
  destination: "",
  endDate: "",
  expenses: null,
  formType: null,
  hasBudget: false,
  hasRecurring: false,
  id: 0,
  integratedWorkflowResult: null,
  integratedWorkflowStatusCode: 0,
  isDelivered: false,
  isExcludeFromBatchExports: false,
  isItAbroad: false,
  logoExported: false,
  name: "",
  ohpCodeId: 0,
  origin: null,
  reportType: 0,
  sendDate: "",
  startDate: "",
  status: 0,
  statusText: "",
  subCompanyId: 0,
  subCompanyName: "",
  tag_Lookup: "",
  tag_LookupId: 0,
  totalAmount: 0,
  totalConfirmation: null,
  tripReport: null,
  tripReportId: 0,
  updateDate: "",
  user: {},
  userId: 0,
  vehicle: null,
  workflows: [],
  note: "",
  delegatedUserId: null,
};

export const emptyCreateReport: CreateReport = {
  name: "",
  delegatedUserId: null,
  subCompanyId: null,
  user: {},
};

const emptyTripReport: TripReport = {
  id: 0,
  reportId: 0,
  firstName: "",
  lastName: "",
  tckn: "",
  dateOfBirth: "",
  gsm: "",
  email: "",
  departman: "",
  position: "",
  tripApprover: 0,
  invoiceApprover: 0,
  invoiceCompany: 0,
  tripReason: "",
  tripLocation: "",
  departureDate: "",
  returnDate: "",
  firstHotelName: "",
  secondHotelName: "",
  hotelEntryDate: "",
  hotelExitDate: "",
  secondHotelEntryDate: "",
  secondHotelExitDate: "",
  departureAirport: "",
  returnAirport: "",
  flightDepartureDate: "",
  flightReturnDate: "",
  vehicle: "",
  origin: "",
  destination: "",
  originDate: "",
  destinationDate: "",
  rentalCarOrigin: "",
  rentalCarOriginDate: "",
  rentalCarDestination: "",
  rentalCarDestinationDate: "",
  driverLicenseNo: "",
  driverLicensePlace: "",
  driverLicenseClass: "",
  driverLicenseDate: "",
  passportNo: "",
  passportValidityDate: "",
  visaStartingDate: "",
  visaCountry: "",
  tripApproverMail: "",
  invoiceApproverEmail: "",
  invoiceCompanyText: "",
  cityId: 0,
  isItAbroad: false,
};



export const emptyBranch: WorkflowBranch = {
  index: 0,
  condition: {
    triggerType: [],
    conditionText: ""
  },
  approvers: []
};

export const emptyStep : WorkflowStep = {
  startIndex: 0,
  endIndex: 0,
  branches: [],
}

export const emptyCustomReportForm: CustomReportForm = {
  userBySubCompyList: [],
  report: {
    id: 0,
    userId: 0,
    approverUserId: 0,
    name: "",
    logoExported: false,
    totalAmount: 0,
    comment: "",
    currency: 0,
    currencyText: "",
    status: 0,
    statusText: "",
    sendDate: "",
    createDate: "",
    user: {},
    approver: {},
    expenses: {},
    workflows: [],
    hasRecurring: false,
    totalConfirmation: 0,
    subCompanyId: 0,
    updateDate: "",
    approvedDate: "",
    subCompanyName: "",
    reportType: 0,
    formType: {
      id: 0,
      companyId: 0,
      name: "",
      createDate: "",
      status: 0,
    },
    customFields: [
      {
        id: 0,
        companyId: 0,
        subCompanyId: 0,
        fieldName: "",
        valueType: 0,
        fieldType: 0,
        customReportId: 0,
        isRequired: false,
        createDate: "",
        status: 0,
        customValue: null,
        customFieldValues: [],
      },
    ],
    customReportType: null,
    hasBudget: false,
    integratedWorkflowResult: null,
    integratedWorkflowStatusCode: 0,
    vehicle: null,
    origin: null,
    destination: null,
    startDate: null,
    endDate: null,
    tripReportId: null,
    description: "",
    ohpCodeId: 0,
    isItAbroad: false,
    tripReport: emptyTripReport,
    advanceReport: {
      id: 0,
      reportId: 0,
      conversionAmount: 0,
      currencyRate: 0,
      cityId: 0,
      country: "",
      day: "",
    },
    denialNote: null,
    advanceReportId: null,
    tag_LookupId: null,
    tag_Lookup: {},
    isDelivered: false,
    isExcludeFromBatchExports: false,
  },
};

export const tripReportCategories = [
  {
    title: "personalInfo",
    fields: ["firstName", "lastName", "tckn", "dateOfBirth", "gsm", "email"],
  },
  {
    title: "approvers",
    fields: ["tripApproverMail", "invoiceApproverEmail"],
  },
  {
    title: "trip",
    fields: ["tripReason", "tripLocation"],
  },
  {
    title: "tripDates",
    fields: ["departureDate", "returnDate"],
  },
  {
    title: "firstHotelInfo",
    fields: ["firstHotelName", "hotelEntryDate", "hotelExitDate"],
  },
  {
    title: "secondHotelInfo",
    fields: ["secondHotelName", "secondHotelEntryDate", "secondHotelExitDate"],
  },
  { title: "airport", fields: ["departureAirport", "returnAirport"] },
  { title: "flightDates", fields: ["flightDepartureDate", "flightReturnDate"] },
  { title: "route", fields: ["origin", "destination"] },
  {
    title: "routeDates",
    fields: ["originDate", "destinationDate"],
  },
  {
    title: "rental",
    fields: [
      "vehicle",
      "rentalCarOrigin",
      "rentalCarOriginDate",
      "rentalCarDestination",
      "rentalCarDestinationDate",
    ],
  },
  {
    title: "driver",
    fields: [
      "driverLicenseNo",
      "driverLicensePlace",
      "driverLicenseClass",
      "driverLicenseDate",
    ],
  },
  {
    title: "visaPassport",
    fields: [
      "passportNo",
      "passportValidityDate",
      "visaStartingDate",
      "visaCountry",
    ],
  },
];
